# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b79fe9f36c83e58a61f06a9c90760497c4d20fb755b2774c9e337add65a41788ff534deb42e3461e0007938d72d86cd48e453ff2b0c3be4e352d3713fbfba7e

test:
  secret_key_base: c0bffd7ba48dc1dc849a9061b3e4bd3c25b4cb27c4405eb9dcdc02fd3f70f99e487426fbc34aa48f30ae95de3e02a0ad9a6a75567d1975dec75eb7c18f0623aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
